--TODO: убрать перед сдачей проекта (наверное)
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS rating;
DROP TABLE IF EXISTS film;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS friend;
DROP TABLE IF EXISTS friendshipStatus;
DROP TABLE IF EXISTS likes;

CREATE TABLE IF NOT EXISTS genre (
  genreId INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  genreName VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS rating (
  ratingId INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ratingName VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS film (
  filmId INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filmName VARCHAR(255),
  description VARCHAR(255),
  releaseDate TIMESTAMP,
  genreId INT,
  duration INT,
  ratingId VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS users (
  userId INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login VARCHAR(255),
  userName VARCHAR(255),
  email VARCHAR(255),
  birthday TIMESTAMP
);

CREATE TABLE IF NOT EXISTS friend (
  userId INT,
  friendId INT,
  friendshipStatusId INT
);

CREATE TABLE IF NOT EXISTS friendshipStatus (
  friendshipStatusId INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS likes (
  filmId INT,
  userId INT
);

COMMENT ON COLUMN genre.genreName IS 'Жанр фильма';

COMMENT ON COLUMN rating.ratingName IS 'Возрастной рейтинг';

COMMENT ON COLUMN film.filmName IS 'Название фильма';

COMMENT ON COLUMN film.description IS 'Описание фильма';

COMMENT ON COLUMN film.releaseDate IS 'Дата выхода фильма';

COMMENT ON COLUMN film.duration IS 'Длительность фильма в минутах';

COMMENT ON COLUMN users.login IS 'Логин пользователя';

COMMENT ON COLUMN users.userName IS 'Имя пользователя';

COMMENT ON COLUMN users.email IS 'Электронная почта пользователя';

COMMENT ON COLUMN users.birthday IS 'День рождения пользователя';

COMMENT ON COLUMN friendshipStatus.status IS 'Статус дружбы между пользователями';